# SPDX-License-Identifier: Unlicense OR 0BSD
name: "hxltm-action"
description: "GitHub Action for HXLM (Humanitarian Exchange Language Terminologium Multilinguam)"
inputs:
  bin:
    description: "The executable to run."
    required: true
  args:
    description: "The input file for the program defined by bin parameter"
    required: false
    default: "fontem.ext"
  infile:
    description: "The input file for the program defined by bin parameter"
    required: false
    default: "fontem.ext"
  outfile:
    description: "The input file for the program defined by bin parameter"
    required: false
    default: "objectivum.ext"

  # crudum-non-securum:
  #   description: "Low level raw command to pass to dockerized container."
  #   required: false
  #   default: "vacuum"
outputs:
  # time: # id of output
  #   description: 'The time we greeted you'
  resultatum:
    description: "stdout of commmand"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.bin }}
    - ${{ inputs.infile }}
    - ${{ inputs.outfile }}
