# SPDX-License-Identifier: Unlicense OR 0BSD
name: "Actions for HXLTM - the Multilingual Terminology in HXL"
description: |
  GitHub Action for HXLTM (Multilingual Terminology in Humanitarian Language
  Exchange). HXLTM allows store terminology and translation memory. This action
  allow use HXLTM pivot standard to export and import(*):
  TBX (TermBase eXchange), TMX (Translation Memory eXchange),
  XLIFF (XML Localization Interchange File Format),
  UTX (Universal Terminology eXchange),
  XML (free user-configurable schemas),
  CSV, XLSX (Microsoft Excel), and much more!
branding:
  icon: 'hash'
  color: 'blue'
inputs:
  bin:
    description: "The executable to run."
    required: true
  infile:
    description: "The input file for the program defined by bin parameter"
    required: false
    default: "fontem.ext"
  outfile:
    description: "The input file for the program defined by bin parameter"
    required: false
    default: "objectivum.ext"
  args:
    description: "Arguments passed for the program defined by bin parameter."
    required: false
    # default: "fontem.ext"

  # crudum-non-securum:
  #   description: "Low level raw command to pass to dockerized container."
  #   required: false
  #   default: "vacuum"
outputs:
  # time: # id of output
  #   description: 'The time we greeted you'
  resultatum:
    description: "stdout of commmand"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.bin }}
    - ${{ inputs.infile }}
    - ${{ inputs.outfile }}
    - ${{ inputs.args }}
