on: [push]

jobs:
  hxltm-testum:
    runs-on: ubuntu-latest
    name: hxltm-action ego testum
    steps:

      # @see https://github.com/actions/checkout
      - name: Checkout the git repository to the actions temporary host runner
        uses: actions/checkout@v2
        # with:
        #   path: main

      #### bin --help __________________________________________________________
      - name: "hxltmcli --help"
        uses: ./
        with:
          bin: "hxltmcli"
          args: "--help"

      - name: "hxltmdexml --help"
        uses: ./
        with:
          bin: "hxltmdexml"
          args: "--help"

      # - name: "csv2po --help"
      #   uses: ./
      #   continue-on-error: true
      #   with:
      #     bin: "csv2po"
      #     args: "--help"

      - name: "hxltag --help (To HXLate tabular data before use with HXL, including HXLTM)"
        uses: ./
        continue-on-error: true
        with:
          bin: "hxltag"
          args: "--help"

      #### Get additional test data and put on data/ ___________________________
      - run: wget https://github.com/fititnt/hxltm-action-example/archive/refs/heads/main.zip
      - run: unzip main.zip
      - run: cp -r hxltm-action-example-main/data/ data/
      - run: find data/

      #### Quick general tests _________________________________________________
      - name: "hxltmcli --objectivum-TBX-Basim data/exemplum/hxltm-exemplum-linguam.tm.hxl.csv data/exemplum/resultatum/de-hxltm/hxltm-exemplum-linguam.tbx"
        uses: ./
        continue-on-error: true
        with:
          bin: "hxltmcli"
          args: "--objectivum-TBX-Basim"
          infile: data/exemplum/hxltm-exemplum-linguam.tm.hxl.csv
          outfile: data/exemplum/resultatum/de-hxltm/hxltm-exemplum-linguam.tbx
          working_languages: |
            arb-Arab@ar,
            por-Latn@pt,
            hin-Deva@hi,
          auxiliary_languages: |
            eng-Latn@en

      # - name: Hello world action step
      #   uses: ./ # Uses an action in the root directory
      #   id: hello
      #   with:
      #     who-to-greet: "Mona the Octocat"
      # # Use the output from the `hello` step
      # - name: Get the output time
      #   run: echo "The time was ${{ steps.hello.outputs.time }}"

      # - run: "hxltmcli --help"
      #   continue-on-error: true

      # - name: hxltmcli --help
      #   id: hello
      #   uses: ./
      #   with:
      #     crudum-non-securum: "hxltmcli --help"

      # - run: sudo apt-get update && sudo apt-get install tree -y
      #   continue-on-error: true

      # - run: tree -a
      #   continue-on-error: true

      # - run: ls .github/hxltm/
      #   continue-on-error: true

      # - run: ls ./
      #   continue-on-error: true

      # - run: ls -lha ./
      #   continue-on-error: true

      # - run: ls -lha ./tests/
      #   continue-on-error: true

      # - run: ls -lha ./tests/result/
      #   continue-on-error: true

      #### Old tests (needs be removed) ________________________________________
      # TODO: delete the tests/ folder and use files from remote repository

      - name: 'hxltmcli --objectivum-TBX-Basim tests/hxltm-exemplum-linguam.tm.hxl.csv tests/result/objectivum.tbx'
        id: exemplum_1
        uses: ./
        with:
          bin: "hxltmcli"
          args: "--objectivum-TBX-Basim"
          infile: "tests/hxltm-exemplum-linguam.tm.hxl.csv"
          outfile: "tests/result/objectivum.tbx"

      - name: 'hxltmcli --objectivum-TMX tests/hxltm-exemplum-linguam.tm.hxl.csv tests/result/objectivum.tmx'
        id: exemplum_2
        continue-on-error: true
        uses: ./
        with:
          bin: "hxltmcli"
          args: "--objectivum-TMX"
          infile: "tests/hxltm-exemplum-linguam.tm.hxl.csv"
          outfile: "tests/result/objectivum.tmx"

      - name: 'hxltmcli --objectivum-UTX tests/hxltm-exemplum-linguam.tm.hxl.csv tests/result/objectivum.utx'
        id: exemplum_3
        continue-on-error: true
        uses: ./
        with:
          bin: "hxltmcli"
          args: "--objectivum-UTX"
          infile: "tests/hxltm-exemplum-linguam.tm.hxl.csv"
          outfile: "tests/result/objectivum.utx"

      # - name: 'hxltmdexml --agendum-linguam por-Latn@pt tests/hxltm-exemplum-linguam.tbx tests/result/objectivum-de-tbx.tm.hxl.csv'
      #   id: exemplum_4
      #   continue-on-error: true
      #   uses: ./
      #   with:
      #     bin: "hxltmdexml"
      #     args: "--agendum-linguam por-Latn@pt"
      #     infile: "tests/hxltm-exemplum-linguam.tm.hxl.csv"
      #     outfile: "tests/result/objectivum-de-tbx.tm.hxl.csv"

      - name: hello rexemplum_1esultatum
        run: echo "hello ${{ steps.exemplum_1.outputs.resultatum }}"

      - run: find ./tests/result/
        continue-on-error: true

      - run: find data/
        continue-on-error: true

        #### Upload artifacts for inspection ___________________________________
      # @see https://github.com/actions/upload-artifact
      - uses: actions/upload-artifact@v2
        # continue-on-error: true
        # https://github.com/nektos/act#skipping-steps
        if: ${{ !env.ACT }}
        with:
          name: objectivum
          path: tests/result/

      #### Upload results ______________________________________________________
      # @see https://github.com/actions/upload-artifact
      - uses: actions/upload-artifact@v2
        if: ${{ !env.ACT }}
        # continue-on-error: true
        with:
          name: data
          path: data/
          retention-days: 5

      # - run: cat tests/result/objectivum.tbx
      #   continue-on-error: true

      # - run: cat tests/result/objectivum.tmx
      #   continue-on-error: true

      # - run: cat tests/result/objectivum.utx
      #   continue-on-error: true

      # - name: disable workflow commands
      #   run: |
      #     echo '::warning:: this is a warning'
      #     echo "::stop-commands::`echo -n ${{ github.token }} | sha256sum | head -c 64`"
      #     echo '::warning:: this will NOT be a warning'
      #     echo "::`echo -n ${{ github.token }} | sha256sum | head -c 64`::"
      #     echo '::warning:: this is a warning again'

      # - run: "hxlselect --help"
      #   continue-on-error: true
