on: [push]

jobs:
  hxltm-testum:
    runs-on: ubuntu-latest
    name: hxltm-action ego testum
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      # - name: Hello world action step
      #   uses: ./ # Uses an action in the root directory
      #   id: hello
      #   with:
      #     who-to-greet: "Mona the Octocat"
      # # Use the output from the `hello` step
      # - name: Get the output time
      #   run: echo "The time was ${{ steps.hello.outputs.time }}"

      # - run: "hxltmcli --help"
      #   continue-on-error: true

      # - name: hxltmcli --help
      #   id: hello
      #   uses: ./
      #   with:
      #     crudum-non-securum: "hxltmcli --help"

      # - run: sudo apt-get update && sudo apt-get install tree -y
      #   continue-on-error: true

      # - run: tree -a
      #   continue-on-error: true

      # - run: ls .github/hxltm/
      #   continue-on-error: true

      # - run: ls ./
      #   continue-on-error: true

      - run: ls -lha ./
        continue-on-error: true

      - run: ls -lha ./tests/
        continue-on-error: true

      - run: ls -lha ./tests/result/
        continue-on-error: true

      - name: hxltmcli --objectivum-TBX-Basim hxltm-exemplum-linguam.tm.hxl.csv hxltm-exemplum-linguam.tbx
        id: exemplum_1
        uses: ./
        with:
          bin: "hxltmcli"
          args: "--objectivum-TBX-Basim"
          infile: "tests/hxltm-exemplum-linguam.tm.hxl.csv"
          outfile: "tests/result/objectivum.tbx"

      - name: hxltmcli --objectivum-TMX hxltm-exemplum-linguam.tm.hxl.csv hxltm-exemplum-linguam.tmx
        id: exemplum_2
        continue-on-error: true
        uses: ./
        with:
          bin: "hxltmcli"
          args: "--objectivum-TMX"
          infile: "tests/hxltm-exemplum-linguam.tm.hxl.csv"
          outfile: "tests/result/objectivum.tmx"

      - name: hxltmcli --objectivum-UTX hxltm-exemplum-linguam.tm.hxl.csv hxltm-exemplum-linguam.utx
        id: exemplum_2
        continue-on-error: true
        uses: ./
        with:
          bin: "hxltmcli"
          args: "--objectivum-TMX"
          infile: "tests/hxltm-exemplum-linguam.tm.hxl.csv"
          outfile: "tests/result/objectivum.utx"

      - name: hello rexemplum_1esultatum
        run: echo "hello ${{ steps.exemplum_1.outputs.resultatum }}"

      - run: ls -lha ./tests/result/
        continue-on-error: true

      - run: cat tests/result/objectivum.tbx
        continue-on-error: true

      - run: cat tests/result/objectivum.tmx
        continue-on-error: true

      - run: cat tests/result/objectivum.utx
        continue-on-error: true

      # - name: disable workflow commands
      #   run: |
      #     echo '::warning:: this is a warning'
      #     echo "::stop-commands::`echo -n ${{ github.token }} | sha256sum | head -c 64`"
      #     echo '::warning:: this will NOT be a warning'
      #     echo "::`echo -n ${{ github.token }} | sha256sum | head -c 64`::"
      #     echo '::warning:: this is a warning again'

      # - run: "hxlselect --help"
      #   continue-on-error: true
